apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - alertmanager/argocd.yaml
  - grafana/argocd.yaml
  - kube-state-metrics/argocd.yaml
  - loki/argocd.yaml
  - node-exporter/argocd.yaml
  - prometheus/argocd.yaml
  - promtail/argocd.yaml
  - goldilocks/argocd.yaml
  - trivy/argocd.yaml
  - helm-dashboard/argocd.yaml