apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Monitoring and observability stack
  - alertmanager/argocd/alertmanager.yaml
  - grafana/argocd/grafana.yaml
  - kube-state-metrics/argocd/kube-state-metrics.yaml
  - loki/argocd/loki.yaml
  - node-exporter/argocd/node-exporter.yaml
  - prometheus/argocd/prometheus.yaml
  - promtail/argocd/promtail.yaml
