apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goldilocks-dashboard-ingress
  namespace: goldilocks
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    haproxy.org/ssl-redirect: "true"
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - goldilocks0213.kro.kr
      secretName: goldilocks-dashboard-tls
  rules:
    - host: goldilocks0213.kro.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goldilocks-dashboard
                port:
                  number: 80
